services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_DB: metadata_db
      POSTGRES_USER: capstone
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/initdb:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U capstone -d metadata_db || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  db_data:
