services:
  db:
    image: ${POSTGRES_IMAGE}
    restart: always
    environment:
      APP_PASSWORD_FILE: ${APP_PASSWORD_FILE}
      APP_USER: ${APP_USER}
      APP_DB: ${APP_DB}

      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_FILE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./docker/db/initdb:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/
    secrets:
      - db_admin_password
      - db_app_password
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" || exit 1',
        ]
      interval: 30s
      timeout: 5s
      retries: 3

secrets:
  db_admin_password:
    file: ./secrets/db_admin_password
  db_app_password:
    file: ./secrets/db_app_password
volumes:
  db_data:
